<#
    pack-nexus.ps1 - builds the Nexus Mods upload archive for Time Never Stops.

    build-pack.ps1 runs this automatically after the two Thunderstore packages, so a normal
    .\run-build.ps1 produces all three. Run it by hand only when you want to repack without
    rebuilding:

        powershell -ExecutionPolicy Bypass -File .\packaging\nexus\pack-nexus.ps1

    It reads from TNS_Project\bin\ and does NOT compile anything, so a hand run packages
    whatever the last build left there. The version comes from Version.props, same as
    everything else; pass -Version only to override it deliberately.

    WHY THE LAYOUT IS WHAT IT IS
    ----------------------------
    Thunderstore gets two separate packages, one per build, because r2modman and Gale install
    a package wholesale and a player picks the right one on the website. Nexus is one mod page
    with one download, so BOTH builds go in the archive and the choice moves into the install.

    The zip root therefore holds `Mono\Mods\` and `IL2CPP\Mods\` rather than a single `Mods\`.
    A manual installer opens the folder matching their game and drags `Mods` onto the game
    directory; Vortex and MO2 read `fomod\` and turn the same choice into a radio button. There
    is deliberately no unconditional file in the archive - installing both DLLs is the one
    outcome nobody wants.
#>
[CmdletBinding()]
param(
    # Defaults to <ModVersion> from Version.props. Stamped into fomod\info.xml and the zip name.
    [string]$Version,

    # Repo root. Defaults to two levels up from this script (packaging\nexus\ -> repo root).
    [string]$RepoRoot
)

$ErrorActionPreference = 'Stop'

if (-not $RepoRoot) { $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path }

if (-not $Version) {
    $propsPath = Join-Path $RepoRoot 'Version.props'
    if (-not (Test-Path -LiteralPath $propsPath)) { throw "pack-nexus: Version.props not found at $propsPath" }
    $raw = Get-Content -LiteralPath $propsPath -Raw
    if ($raw -match '<ModVersion>(.+?)</ModVersion>') { $Version = $Matches[1].Trim() }
    else { throw "pack-nexus: could not parse <ModVersion> from Version.props" }
}

$nexusDir = $PSScriptRoot
$stage    = Join-Path $nexusDir 'obj\stage'
$outDir   = Join-Path $RepoRoot 'Packages'
$zipPath  = Join-Path $outDir "TimeNeverStops-$Version.zip"

# Everything the archive needs, and where it comes from. Checked up front so a missing input
# fails with the path that is wrong instead of producing a quietly incomplete zip.
$srcIl2cpp  = Join-Path $RepoRoot 'TNS_Project\bin\IL2CPP\net6.0\TimeNeverStops_IL2Cpp.dll'
$srcMono    = Join-Path $RepoRoot 'TNS_Project\bin\MONO\netstandard2.1\TimeNeverStops_Mono.dll'
$srcIcon    = Join-Path $RepoRoot 'icon.png'
$srcChanges = Join-Path $RepoRoot 'CHANGELOG.md'
$srcReadme  = Join-Path $RepoRoot 'README.md'
$srcManual  = Join-Path $nexusDir 'MANUAL-INSTALL.txt'
$srcInfo    = Join-Path $nexusDir 'fomod\info.xml'
$srcModCfg  = Join-Path $nexusDir 'fomod\ModuleConfig.xml'
$srcSchema  = Join-Path $nexusDir 'schema\XmlScript5.0.xsd'

$required = @($srcIl2cpp, $srcMono, $srcIcon, $srcChanges, $srcReadme, $srcManual,
              $srcInfo, $srcModCfg, $srcSchema)
$missing = $required | Where-Object { -not (Test-Path -LiteralPath $_) }
if ($missing) {
    throw "pack-nexus: missing input(s):`n  " + ($missing -join "`n  ") +
          "`n  (Both configurations must be built. Run .\run-build.ps1 -SkipPack first.)"
}

# The single failure this script exists to prevent, after shipping the wrong build: shipping a
# STALE build. Both DLLs carry <ModVersion> as their FileVersion (generated by the csproj), so
# a mismatch means bin\ predates the version bump and the zip would be a lie about its contents.
foreach ($dll in @($srcIl2cpp, $srcMono)) {
    $fv = (Get-Item -LiteralPath $dll).VersionInfo.FileVersion
    if (-not $fv.StartsWith("$Version.")) {
        throw "pack-nexus: '$([System.IO.Path]::GetFileName($dll))' is version $fv but this pack is $Version. " +
              "That bin\ output predates the current Version.props - rebuild before packaging."
    }
}

Write-Host "pack-nexus: staging Time Never Stops $Version"

# Stage from scratch every time. Reusing the folder is how a file deleted from the mod keeps
# shipping for another three releases.
if (Test-Path -LiteralPath $stage) { Remove-Item -LiteralPath $stage -Recurse -Force }
$il2cppDir = Join-Path $stage 'IL2CPP\Mods'
$monoDir   = Join-Path $stage 'Mono\Mods'
$fomodDir  = Join-Path $stage 'fomod'
foreach ($d in @($il2cppDir, $monoDir, $fomodDir)) {
    New-Item -ItemType Directory -Path $d -Force | Out-Null
}

# --- the two builds : one of these is what the player ends up with, never both -------------
Copy-Item -LiteralPath $srcIl2cpp -Destination $il2cppDir
Copy-Item -LiteralPath $srcMono   -Destination $monoDir

# --- fomod\ : the guided installer Vortex and MO2 read -------------------------------------
(Get-Content -LiteralPath $srcInfo -Raw).Replace('@VERSION@', $Version) |
    Set-Content -LiteralPath (Join-Path $fomodDir 'info.xml') -Encoding utf8 -NoNewline
Copy-Item -LiteralPath $srcModCfg -Destination $fomodDir
Copy-Item -LiteralPath $srcIcon   -Destination (Join-Path $fomodDir 'icon.png')

# --- archive root : what a player sees first when they open the zip ------------------------
Copy-Item -LiteralPath $srcChanges -Destination $stage
Copy-Item -LiteralPath $srcReadme  -Destination $stage
Copy-Item -LiteralPath $srcManual  -Destination (Join-Path $stage 'READ ME FIRST - Manual Install.txt')

# --- FOMOD validation : both halves of what Vortex actually does ---------------------------
# Schema validation alone is not enough: pointing a validator at the 5.0 schema bypasses the
# version detection that is the thing most likely to be broken. So run the detection too.
$stagedModCfg = Join-Path $fomodDir 'ModuleConfig.xml'
$modCfgText   = Get-Content -LiteralPath $stagedModCfg -Raw

# 1. Version detection, byte-for-byte the regex from Nexus-Mods/fomod-installer
#    (XmlScriptType.cs, RegexVersion). Singleline only - deliberately NOT IgnoreCase, because
#    the real one is not either, and a check more lenient than the tool it models is useless.
$rxVersion = New-Object System.Text.RegularExpressions.Regex(
    'xsi:noNamespaceSchemaLocation="[^"]*((XmlScript)|(ModConfig))(.*?).xsd',
    [System.Text.RegularExpressions.RegexOptions]::Singleline)
# Vortex takes the FIRST match in the file, so a second mention of the attribute name - in a
# comment, say - is a decoy that can capture the match and hand back a garbage version.
$attrCount = ([regex]::Matches($modCfgText, [regex]::Escape('noNamespaceSchemaLocation='))).Count
if ($attrCount -ne 1) {
    throw "pack-nexus: fomod\ModuleConfig.xml mentions noNamespaceSchemaLocation $attrCount times, expected exactly 1. Vortex matches the FIRST occurrence in raw text, so any extra mention - even inside a comment - can hijack version detection. Remove it."
}

$m = $rxVersion.Match($modCfgText)
$detected = if ($m.Success -and $m.Groups[4].Value) { $m.Groups[4].Value } else { '1.0' }
if ($detected -ne '5.0') {
    throw "pack-nexus: Vortex would read this FOMOD as XmlScript $detected, not 5.0. The xsi:noNamespaceSchemaLocation string in fomod\ModuleConfig.xml is wrong - check the casing of 'ModConfig', the 'xsi:' prefix, and that there is no whitespace around the '='. At 1.0 the schema predates moduleImage and installSteps, and Vortex rejects the installer with a misleading line number."
}

# 2. Schema validation against the version detection just resolved to.
$vset = New-Object System.Xml.XmlReaderSettings
$vset.ValidationType = [System.Xml.ValidationType]::Schema
$null = $vset.Schemas.Add($null, $srcSchema)
$vErrors = New-Object System.Collections.ArrayList
$vset.add_ValidationEventHandler([System.Xml.Schema.ValidationEventHandler] {
    param($s, $e)
    if ($e.Severity -eq [System.Xml.Schema.XmlSeverityType]::Error) {
        [void]$vErrors.Add("Line $($e.Exception.LineNumber), Pos $($e.Exception.LinePosition): $($e.Message)")
    }
})
$vr = [System.Xml.XmlReader]::Create($stagedModCfg, $vset)
try { while ($vr.Read()) { } }
catch { [void]$vErrors.Add("fatal: $($_.Exception.Message)") }
finally { $vr.Close() }
if ($vErrors.Count -gt 0) {
    throw "pack-nexus: fomod\ModuleConfig.xml fails XmlScript 5.0 validation:`n  " + ($vErrors -join "`n  ")
}
Write-Host "pack-nexus: fomod validates as XmlScript $detected"

New-Item -ItemType Directory -Path $outDir -Force | Out-Null
if (Test-Path -LiteralPath $zipPath) { Remove-Item -LiteralPath $zipPath -Force }

# CreateFromDirectory rather than Compress-Archive. Compress-Archive has a long history of
# emitting backslash separators on Windows PowerShell 5.1, and this archive goes to strangers
# with unknown extractors. The trailing $false means "do not nest everything under a folder
# named after the staging directory".
#
# Do NOT try to verify separators by reading ZipArchiveEntry.FullName back - on .NET Framework
# that property rewrites '/' to the platform separator as it reads, so a correct archive looks
# broken and a broken one looks correct.
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::CreateFromDirectory(
    $stage, $zipPath, [System.IO.Compression.CompressionLevel]::Optimal, $false)

# Guard against a silently incomplete archive - a mistyped staging path copies nothing and
# throws nothing, and the failure only shows up as a mod that will not load.
$staged = (Get-ChildItem -LiteralPath $stage -Recurse -File).Count
$zip = [System.IO.Compression.ZipFile]::OpenRead($zipPath)
try { $packed = @($zip.Entries | Where-Object { $_.Length -gt 0 -or $_.Name }).Count }
finally { $zip.Dispose() }
if ($packed -lt $staged) {
    throw "pack-nexus: staged $staged files but the archive holds $packed. Do not upload it."
}

$sizeKb = '{0:N0}' -f ((Get-Item -LiteralPath $zipPath).Length / 1KB)
Write-Host "pack-nexus: wrote $zipPath ($sizeKb KB, $packed files, both builds)"
