[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "DropDaDeuce"
name = "TimeNeverStops_Mono"
versionNumber = "1.3.0"
description = "Time no longer stops at 4AM. Configurable day speed multiplier. (Mono build)"
websiteUrl = "https://github.com/DropDaDeuce/Time-Never-Stops"
containsNsfwContent = false

[package.dependencies]
LavaGang-MelonLoader = "0.7.1"

[build]
icon = "../icon.png"
readme = "../README.md"
outdir = "../Packages"

[[build.copy]]
source = "../TNS_Project/bin/MONO/netstandard2.1/TimeNeverStops_Mono.dll"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[publish]
communities = [ "schedule-i" ]

[publish.categories]
schedule-i = [ "Mods", "Mono" ]